.gitignore
components/DelegatesList.tsx
components/Filters/InterestsFilter.tsx
components/Filters/OrderByFilters.tsx
components/Filters/SearchFilter.tsx
contexts/delegates.tsx

feat: interests filter

---

components/DelegateCard.tsx
components/DelegatesList.tsx
components/Filters/PeriodFilter.tsx
components/Modals/UserProfile/Statement.tsx
contexts/delegates.tsx
resources/aave/index.ts
resources/dimo/index.ts
resources/dydx/index.ts
resources/gitcoin/index.ts
resources/op/index.ts
resources/optimism/index.ts
resources/pooltogether/index.ts
resources/ssvnetwork/index.ts
resources/yamfinance/index.ts
types/contexts/delegates.ts
types/resources/config.ts

feat: adding 180d, healthScore on stats, removing retry of pitchData

---

components/DelegateCard.tsx
components/DelegatesList.tsx
contexts/delegates.tsx
types/IDelegate.ts
types/IDelegateFromAPI.ts

feat: add description on workstreams, fixed card responsiveness, changing text, refactored params

---

components/DelegatesList.tsx
components/Icons/DiscordIcon.tsx
components/Icons/index.ts
components/Modals/Linking/Twitter/ESteps.ts
components/Modals/Linking/Twitter/Step1.tsx
components/Modals/Linking/Twitter/Step2.tsx
components/Modals/Linking/Twitter/Step3.tsx
components/Modals/Linking/Twitter/StepVerified.tsx
components/Modals/Linking/Twitter/index.tsx
components/Modals/Linking/index.ts
components/Modals/UserProfile/Handles.tsx
components/Modals/UserProfile/Header.tsx
components/Modals/UserProfile/index.tsx
contexts/delegates.tsx
helpers/api.ts
hooks/useToasty.ts
types/Modal/UserProfile.ts

feat: twitter linking and header with social media icons

---

components/Modals/UserProfile/Header.tsx
components/Modals/UserProfile/WithdrawDelegation/WithdrawPopover.tsx
components/Modals/UserProfile/WithdrawDelegation/index.tsx
components/Modals/UserProfile/index.tsx
contexts/delegates.tsx
types/IDelegate.ts
types/IDelegateFromAPI.ts
types/Modal/UserProfile.ts

feat: withdrawn functionality

---

components/DelegateCard/index.tsx
components/ScoreBreakdown/index.tsx
contexts/scoreBreakdown.tsx

feat: forum score breakdown

---

components/pages/faq/index.tsx
containers/faq.tsx
contexts/dao.tsx
pages/_sites/[site]/faq.tsx
public/daos/dydx/faq.md

fix: faq file not found

---

contexts/editStatement.tsx

feat: adding dynamics interests

---

middleware.ts

feat: starknet custom domain

---

layouts/main.tsx
package.json
yarn.lock

feat: hotjar

---

components/Modals/UserProfile/Header.tsx
contexts/auth.tsx
contexts/editStatement.tsx
helpers/cookies.ts

feat: edit statement as an admin

---

contexts/editStatement.tsx

fix: wrong interests props

---

components/Modals/Linking/Twitter/Step3.tsx
components/Modals/UserProfile/WithdrawDelegation/index.tsx

feat: changed the twitter verification message

---

components/pages/faq/index.tsx
public/daos/dydx/faq.md

fix: links should open in new tab for md

---

hooks/useDelegation.ts
package.json
resources/aave/index.ts
resources/apecoin/index.ts
resources/developer/index.ts
resources/dimo/index.ts
resources/dydx/index.ts
resources/element-finance/index.ts
resources/gitcoin/index.ts
resources/op/index.ts
resources/optimism/index.ts
resources/pooltogether/index.ts
resources/ssvnetwork/index.ts
resources/starknet/index.ts
resources/yamfinance/index.ts
yarn.lock

We had some warning and errors on application caused by wagmi, so i upgraded wagmi and rainbowkit

feat: updating wagmi and rainbowkit version

---

components/Modals/UserProfile/VotingHistory/ContrarionIndex.tsx
components/Modals/UserProfile/VotingHistory/DelegatedVotesChanges.tsx
components/Modals/UserProfile/VotingHistory/index.tsx
contexts/votes.tsx
types/contexts/index.ts
types/contexts/votes.ts

feat: contrarion index

---

components/Filters/DelegateStatusFilter.tsx
components/Filters/OrderFilter.tsx
components/Filters/PeriodFilter.tsx
components/Filters/StatFilter.tsx
contexts/delegates.tsx

feat: filters and sortings on url

---

components/Modals/Linking/Forum/index.tsx
components/Modals/Linking/Twitter/index.tsx
components/Modals/UserProfile/Handles.tsx
components/Modals/UserProfile/Header.tsx
types/resources/config.ts

feat: forum disable by user creation time

---

components/Modals/Delegate/DelegateModalFooter.tsx
utils/sendLeadEmail.ts

feat: added dao name on leads

---

resources/starknet/index.ts

> Awaiting starknet data to be loaded in athena

feat: added more stats to starknet

---

components/Modals/UserProfile/Handles.tsx
components/Modals/UserProfile/Header/NavigatorRow.tsx
components/Modals/UserProfile/Header/index.tsx
contexts/editProfile.tsx
package.json
yarn.lock

feat: admin can update twitter handle

---

contexts/delegates.tsx

feat: adding user without delegate can open modal

---

package.json
pages/_app.tsx
yarn.lock

feat: added analytics package

---

components/Modals/UserProfile/VotingHistory/ProposalVote.tsx

feat: votes with nay and nae

---

components/pages/guide/index.tsx
containers/guide.tsx
pages/_sites/[site]/guide.tsx

feat: /guide page

---

components/HeaderHat/HeaderHat.tsx
resources/ssvnetwork/index.ts

feat: ssv faq

---

components/pages/token-holders/PerformanceStats.tsx

fix: fixed voting pct on lookup delegate

---

contexts/governanceVotes.tsx
resources/apecoin/TOKENABI.json
resources/apecoin/index.ts
resources/index.ts
resources/safe/TOKENABI.json
resources/safe/index.ts
resources/ssvnetwork/TOKENABI.json
resources/ssvnetwork/index.ts
resources/starknet/TOKENABI.json
resources/starknet/index.ts
types/resources/config.ts
types/resources/info.ts

feat: adding token contract to apecoin, safe, ssv, starknet

---

resources/dydx/index.ts

- Changing dydx to have discourse as forum

feat: dydx to discourse

---

components/HeaderHat/DelegateLoginButton.tsx
contexts/auth.tsx
contexts/delegates.tsx

fix: new user not having modal open

---

contexts/governanceVotes.tsx

fix: null value on amount

---

components/pages/faq/index.tsx
components/pages/guide/index.tsx

fix: faq and guide not showing up

---

utils/moonbeam/moonriverOnChainProvider.ts
utils/moonbeam/moonriverUndelegateAction.ts

fix: updated subgraph param name

---

components/DelegationPool/index.tsx
components/Modals/Delegate/TrackDelegation.tsx
contexts/delegates.tsx

fix: delegating full balance and blocking with <0.2 votes

---

components/Modals/Delegate/TrackDelegation.tsx
contexts/delegates.tsx
utils/moonbeam/moonriverDelegateAction.ts
utils/moonbeam/moonriverOnChainProvider.ts
utils/moonbeam/moonriverUndelegateAction.ts

feat: undelegate before re-delegation

---

components/Modals/UserProfile/EditStatement/index.tsx
components/Modals/UserProfile/Statement.tsx
components/Modals/UserProfile/ToA/index.tsx

feat: md preview

---

components/Modals/Delegate/TrackDelegation.tsx
contexts/governanceVotes.tsx
resources/moonriver/index.ts
types/resources/config.ts
types/votes/moonbeam.ts
utils/moonbeam/moonbeamwsc.ts
utils/moonbeam/moonriverOnChainProvider.ts

feat: delegate locked tokens

---

components/Modals/Delegate/TrackDelegation.tsx
components/Modals/Linking/Twitter/index.tsx
components/Modals/UserProfile/Handles.tsx
components/Modals/UserProfile/Header/MediaIcon.tsx
contexts/governanceVotes.tsx
utils/moonbeam/moonriverConvictionOptions.ts

fix: moonriver bugs/adjusts

---

components/Modals/Delegate/TrackDelegation.tsx
components/Modals/Delegate/index.tsx

1. Checkout the branch
2. `yarn build`
3. `yarn start`
4. Goto `moonriver.localhost:3000`
5. Disconnect the wallet from the site through metamask
6. Click Delegate button, connect your wallet
7. Modal should open with the correct balance

fix: 0 balance in moonriver yup

---

utils/moonbeam/moonriverDelegateAction.ts
utils/moonbeam/moonriverOnChainProvider.ts

fix: redelegation count wrong for new delegators

---

components/Modals/Linking/Forum/index.tsx

fix: changed forum link url to link/forum

---

components/Modals/Linking/Forum/index.tsx
resources/moonriver/index.ts

fix: Enabled scores to moonriver

---

components/Modals/Linking/Forum/index.tsx

fix: forum linking body param missing

---

components/DelegateCard/index.tsx
components/Modals/Delegate/TrackDelegation.tsx
components/pages/token-holders/UndelegateModal.tsx
utils/moonbeam/moonriverDelegateAction.ts
utils/moonbeam/moonriverOnChainProvider.ts

feat: lock time

---

components/Modals/UserProfile/VotingHistory/ProposalVote.tsx
components/Modals/UserProfile/VotingHistory/index.tsx
components/pages/token-holders/VotingHistory/ProposalVote.tsx
contexts/votes.tsx
hooks/useOffChainVotes.ts
hooks/useOnChainVotes.ts
resources/aave/index.ts
resources/apecoin/index.ts
resources/developer/index.ts
resources/dimo/index.ts
resources/dydx/index.ts
resources/element-finance/index.ts
resources/gitcoin/index.ts
resources/moonbeam/index.ts
resources/moonriver/index.ts
resources/op/index.ts
resources/optimism/index.ts
resources/pooltogether/index.ts
resources/rocketpool/index.ts
resources/safe/index.ts
resources/ssvnetwork/index.ts
resources/starknet/index.ts
resources/yamfinance/index.ts
types/IChainRow.ts
types/resources/theme.ts
utils/GraphQL.ts
utils/checkDecision.ts
utils/moonbeam/moonriverOnChainProvider.ts

feat: not voted yet

---

components/Modals/UserProfile/VotingHistory/ProposalVote.tsx
components/Modals/UserProfile/VotingHistory/index.tsx
components/pages/token-holders/VotingHistory/ProposalVote.tsx
contexts/votes.tsx
hooks/useOffChainVotes.ts
hooks/useOnChainVotes.ts
resources/aave/index.ts
resources/apecoin/index.ts
resources/developer/index.ts
resources/dimo/index.ts
resources/dydx/index.ts
resources/element-finance/index.ts
resources/gitcoin/index.ts
resources/moonbeam/index.ts
resources/moonriver/index.ts
resources/op/index.ts
resources/optimism/index.ts
resources/pooltogether/index.ts
resources/rocketpool/index.ts
resources/safe/index.ts
resources/ssvnetwork/index.ts
resources/starknet/index.ts
resources/yamfinance/index.ts
types/IChainRow.ts
types/resources/config.ts
types/resources/theme.ts
utils/GraphQL.ts
utils/checkDecision.ts
utils/moonbeam/moonriverOnChainProvider.ts
utils/moonbeam/polkassembly.ts

This branch is depending on "not voted yet" branch changes

feat: voting history enhancement

---

components/DelegateCard/index.tsx

feat: adjusting cards to stop overflow

---

contexts/delegates.tsx
contexts/votes.tsx
resources/op/index.ts
resources/optimism/index.ts
utils/optimism/index.ts
utils/optimism/onChainOptimismVotesProvider.ts

feat: optimism on chain votes

---

components/Modals/Delegate/TrackDelegation.tsx

fix: vote value auto fill

---

components/Modals/UserProfile/Handles.tsx
contexts/delegates.tsx
contexts/editProfile.tsx
types/IDelegate.ts
types/IDelegateFromAPI.ts

feat: thread input

---

components/Modals/UserProfile/EndorsementsGiven/index.tsx
components/Modals/UserProfile/EndorsementsReceived/CommentModal.tsx
components/Modals/UserProfile/EndorsementsReceived/index.tsx
components/Modals/UserProfile/Header/index.tsx
components/pages/endorsements/index.tsx
package.json
styles/navigator.css
yarn.lock

fix: style issues on not firefox browsers

---

components/Modals/Endorse/EndorseModal.tsx

fix: using dao chain id for schema

---

components/Modals/Delegate/DelegateModalFooter.tsx
components/Modals/UserProfile/EndorsementsGiven/index.tsx
components/Modals/UserProfile/EndorsementsReceived/index.tsx
components/Modals/UserProfile/Stats/StatsRow.tsx
components/pages/endorsements/index.tsx
resources/gitcoin/index.ts
types/Modal/Endorsements.ts
utils/eas.ts
utils/endorsements/getEndorsementsFromAddress.ts
utils/endorsements/getEndorsementsOfAddress.ts

feat: external link to attestations

---

components/DelegateRegistry/AddToRegistryButton.tsx

fix: rpc url on env

---

components/DelegateRegistry/AddToRegistryButton.tsx

feat: removed whitelist

---

components/Filters/Period.tsx
types/contexts/delegates.ts

feat: add 90 days to filter dropdown

---

.eslintrc.json
components/Carousels/index.tsx
components/DelegateCard/DelegateStat.tsx
components/DelegateCard/StatsCarousel.tsx
components/DelegateCard/index.tsx
components/Modals/UserProfile/SelectSavingMethod.tsx

feat: new card design

---

components/DelegateCard/index.tsx
components/Modals/UserProfile/Handles.tsx
components/Modals/UserProfile/Header/MediaIcon.tsx
components/Modals/UserProfile/Header/index.tsx
contexts/editProfile.tsx

feat: disabling twitter icon

---

components/pages/delegate-compensation/v1.5/Admin/Delegates/DelegateFeedback.tsx
components/pages/delegate-compensation/v1.6/Admin/Delegates/DelegateBP.tsx
components/pages/delegate-compensation/v1.6/Admin/Delegates/DelegateFeedback.tsx
components/pages/delegate-compensation/v1.6/Admin/Delegates/DelegateFinalScore.tsx
components/pages/delegate-compensation/v1.6/Admin/Delegates/DelegateStats.tsx
components/pages/delegate-compensation/v1.6/Admin/Delegates/VotingPowerBreakdownModal.tsx
components/pages/delegate-compensation/v1.6/Admin/ForumActivity/index.tsx
types/delegate-compensation/data.ts

Documentation related:
[VP Score multiplier](https://docs.google.com/document/d/1s2yQVAed6_9Gw0yBlfQNo-6HdmXrTNdb5Gey0DNPjwM/edit?pli=1&tab=t.0)
[Feedback Karma 1.6 Dashboard](https://docs.google.com/document/d/19AxqaFwrflB67C3h7XljqhNzSvH5aEbbtpuKCCQBT70/edit?tab=t.0#heading=h.69g28lb19gnw)

feat: DIP 1.6 changes

---

components/pages/delegate-compensation/v1.6/Admin/Delegates/DelegateFeedbackCalculation.tsx
components/pages/delegate-compensation/v1.6/Admin/Delegates/DelegateFinalScore.tsx
components/pages/delegate-compensation/v1.6/Admin/ForumActivity/index.tsx

fix: TP formula and order

---

containers/delegate-compensation-admin.tsx

feat: adding random param to endpoint

---

components/pages/delegate-compensation/v1.6/Admin/Delegates/DelegateFinalScore.tsx
components/pages/delegate-compensation/v1.6/Admin/Delegates/DelegateStats.tsx
containers/delegate-compensation-admin.tsx
types/delegate-compensation/data.ts

* feat: add penality points to finalScore modal
* fix: remove negative symbol
* improve: DIP April - Penalty breakdown
* chore: force formatting
---------

Feat/add penality points (#411)

---

resources/compound/index.ts

Enable KarmaScore for Compound

feat: enable compound score

---

resources/compound/index.ts

feat: enable compound score (#416)

---

components/BodyTitle.tsx
components/DelegateCard/index.tsx
components/HeaderHat/DelegateLoginButton.tsx
components/HeaderHat/HeaderHat.tsx
public/daos/ssvnetwork/faq.md
resources/ssvnetwork/index.ts
types/resources/config.ts

This PR implements UI improvements and SSV-specific configuration enhancements, with most changes benefiting all DAOs while some being SSV-specific.
**Enhanced Call-to-Action Buttons:**
- **BodyTitle Component**: 
- Changed "View discussion" → "Join discussion" for better engagement
- Changed "Learn more & Get Involved" → "Get Involved" for conciseness
- Added support for `GET_ENVOLVED_URL` config option (falls back to `DAO_URL`)
- Added new "Apply as Delegate" button when `APPLY_AS_DELEGATE_URL` is configured
**Improved Discord Integration:**
- **DelegateCard Component**: Replaced Discord username popover with direct clickable link to Discord profile using proper `DiscordIcon`
**Better Navigation Control:**
- **HeaderHat Component**: Added conditional rendering for Guide link based on …

Feat: SSV Requests
